version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  mongodb:
